### ISSUE TITLE
Build failing with caddy 2.6.4

### ISSUE THREAD

**Issue by davidpanic** [ggicci/caddy-jwt#34]
The plugin cannot be built when using caddy 2.6.4.

```
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc000029260?, 0xc001021f20?}, {0xc0000b4660?, 0xc00031a908?}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000276100, {0xb313d0, 0xc00002a058}, {0x0, 0x0, 0x0})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc000276100, {0xb313d0, 0xc00002a058}, {0x0?, 0x2?, 0x472485?})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0x105
cmd/go/internal/modget.runGet({0xb313d0, 0xc00002a058}, 0xc000028498?, {0xc0000241c0, 0x2, 0x2})
	/usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x45e
main.invoke(0xe2cfc0, {0xc000024190, 0x5, 0x5})
	/usr/local/go/src/cmd/go/main.go:225 +0x34e
main.main()
	/usr/local/go/src/cmd/go/main.go:179 +0x7d1
2023/02/27 10:26:24 [FATAL] exit status 2
```

I'm using the following Dockerfile:

```Dockerfile
FROM caddy:2-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/ggicci/caddy-jwt

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

I believe this to be an upstream issue with go: golang/go#56494

I think all that needs to be updated is the caddy version in the go.mod file.
This is already known by caddy: caddyserver/caddy#5301

**Comment by ggicci** [comment]
Thanks for the report! I will fix it ASAP :)
